# Generated by Django 3.2.6 on 2021-10-18 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='room',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='chat.chatroom'),
            preserve_default=False,
        ),
    ]
